version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    links:
      - mongo

  mongo:
    image: mongo:4.2.2
    volumes:
      - ./data/mongo:/data/db
    expose:
      - "27017"
